modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
[[mods]]
modId="rottenflashusage"
version="0.1"
displayName="Rotten Flash Usage"
credits="Made by Pixeluted, Thanks zKryle for help and TruePenut for awesome textures"
authors="Pixeluted"
description='''
    Rotten Flash Usage will add more usage for rotten flash.
    This mod will allow you to convert rotten flash to charcoal and bone meal!.

    This mod has been made in collaboration with Pixeluted and zkryle!
    
    Made by Pixeluted, Thanks zKryle for help and TruePenut for awesome textures
'''
[[dependencies.rottenflashusage]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rottenflashusage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
